life-is-feudal-your-own/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using life_is_feudal_your_own.utils;
using CoreManagement.Models;
using CoreManagement;
using Newtonsoft.Json;

namespace life_is_feudal_your_own.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult All()
        {
            using(var db = new LifeIsFeudalDb())
            {
                var a = db.Items.ToList().Select(x => new {
                    created_at = x.Created,
                    id = x.Id,
                    name = x.Name,
                    price = x.Price,
                    sub_category = x.SubCategory_Id,
                    category_id = x.Category_Id
                }).OrderBy(x => x.category_id).OrderBy(x => x.sub_category).OrderBy(x => x.name); ;
                return Json(a, JsonRequestBehavior.AllowGet); ;
            }            
        }

        public ActionResult SaveItem(Item item)
        {
            using(var db = new LifeIsFeudalDb())
            {
                if(item.Id == 0)
                {
                    db.Items.Add(item);
                    return Json(item);
                }
                else
                {
                    var findExisting = db.Items.ToList().FirstOrDefault(x => x.Id == item.Id);
                    findExisting.Name = item.Name;
                    findExisting.Price = item.Price;
                    findExisting.SubCategory_Id = item.SubCategory_Id;
                    findExisting.Category_Id = item.Category_Id;
                    db.Entry(findExisting).State = System.Data.Entity.EntityState.Modified;
                    return Json(item);
                }                
            }
        }       
        public ActionResult GetItemQualitiesById(long id)
        {
            using(var db = new LifeIsFeudalDb())
            {
                var ret = db.ItemQualities.Where(x => x.Item_Id == id).ToList().Select(x => new {
                    buy_active = x.BuyActive,
                    id = x.Id,
                    Item_id = x.Item_Id,
                    ItemQualityType_id = x.ItemQualityType_Id,
                    sell_active = x.SellActive,
                    created_at = x.Created
                }); ;
                return Json(ret, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult GetItemsById(long catId,long subId)
        {
            using (var db = new LifeIsFeudalDb())
            {
                var ret = db.Items.Where(x => x.SubCategory_Id == subId && x.Category_Id == catId).ToList()
                    .Select(x=>new {
                        id = x.Id,
                        name = x.Name,
                        price = x.Price
                    });
                return Json(ret, JsonRequestBehavior.AllowGet);
            };

        }
    }
}

life-is-feudal-your-own/Controllers/OrderFormController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Sheets.v4;
using Google.Apis.Sheets.v4.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;
using life_is_feudal_your_own.utils;
using Newtonsoft.Json;
using CoreManagement;
using CoreManagement.Models;

namespace life_is_feudal_your_own.Controllers
{
    public class OrderFormController : Controller
    {
        // GET: OrderForm
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Save(OrderForm product)
        {
            using(var db = new LifeIsFeudalDb())
            {
                try
                {
                    db.OrderForms.Add(product);
                    db.SaveChanges();
                    product.OrderNumber = product.Id.ToString().PadLeft(5, '0');
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    var ret = new
                    {
                        OrderNumber = product.OrderNumber,
                        PlayerName = product.PlayerName
                    };
                    return Json(ret);
                }
                catch (Exception ie)
                {
                    var e = ie;
                    return Json(ie);
                }
            }
        }
        public ActionResult SendOrder(OrderForm order, List<OrderFormProduct> products)
        {

            string htmlBody;// = htmlMessage.CreateHtmlHeader(order);
            using (var db = new LifeIsFeudalDb())
            {
                products.ForEach(x =>
                {
                    x.ItemQuality = db.ItemQualities.FirstOrDefault(y => x.ItemQuality_Id == y.Id);
                });
                order.Products = products;
                htmlBody  = htmlMessage.CreateEmailHtml(order);
                //var itemsSelling = products.Where(x => x.Selling).ToList();
                //var itemsBuying = products.Where(x => !x.Selling).ToList();
                //if(itemsSelling.Count > 0)
                //{
                //    htmlBody += "</br><p>Selling</p>";
                //    htmlBody += htmlMessage.CreateTable(itemsSelling);
                //}
                //if(itemsBuying.Count > 0)
                //{
                //    htmlBody += "</br></br><p>Buying</p>";
                //    htmlBody += htmlMessage.CreateTable(itemsBuying);
                //}
            
            
                SendEmail.SendEmailMessage($"Player Order: {order.PlayerName} Order Number: {order.Id.ToString().PadLeft(5,'0')}",htmlBody);
                return Json(new { success= true,data=new { } });
            }
        }
    }
}

life-is-feudal-your-own/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Caridia Crossroads Market Place</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Order Form", "Index", "OrderForm")</li>
                    <li>@Html.ActionLink("Item Management", "Index", "Item")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - Caridia Crossroads Market Place : Foster Bros</p>
        </footer>
    </div>
    <script src="~/Scripts/deps/lodash.js"></script>
    <script src="~/Scripts/deps/moment.js"></script>
    <script src="~/Scripts/deps/async.min.js"></script>
    <script src="~/Scripts/deps/jquery-3.3.1.slim.js"></script>
    <script src="~/Scripts/deps/jquery-3.3.1.js"></script>
    <script src="~/Scripts/deps/jquery.validate.js"></script>
    <script src="~/Scripts/deps/bootstrap.js"></script>
    <script src="~/Scripts/deps/knockout-3.4.2.js"></script>
    <script src="~/Scripts/deps/modernizr-2.8.3.js"></script>
    <link href="~/Scripts/deps/LifeIsFeudalStyle.css" rel="stylesheet" />
    @RenderSection("modals", required: false)
    @RenderSection("scripts", required: false)

</body>
</html>